### PR TITLE
Fixes xcframework generation issues with Xcode 15

### PR DESCRIPTION
**Pull request by bsneed**
- Pulled Xcodeproj module from SPM 5.7 in as a local module.
- Updated modules and branches for SPM 5.9.

Swift 5.9's toolchain produces errors with the current release, this fixes said issues.

Error Example:
```
Building XCFrameworks ...
warning: unable to restore workspace state: unknown 'WorkspaceStateStorage' version '6' at '/Users/somedude/work/myproject/.build/workspace-state.json'
debug: evaluating manifest for 'myproject' v. unknown
error: missingKey("product_type")
debug: evaluating manifest for 'myproject' v. unknown
error: missingKey("product_type")
Error: fatalError
Done.
```

### CODE REVIEW

**Comment by minuscorp** [comment]
```
error: multiple targets named 'Xcodeproj' in: 'swift-create-xcframework', 'swift-package-manager'; consider using the `moduleAliases` parameter in manifest to provide unique names
```
When trying to `make install` your branch with Swift 5.8 toolchain

**Comment by bsneed** [comment]
@minuscorp These changes are for the 5.9 toolchain, and it is required to build.

**Comment by minuscorp** [comment]
But it breaks older versions so it is not a valid solution.

**Comment by bsneed** [comment]
Ah, I misunderstood your original.  Please see the attached fix.

**Comment by minuscorp** [comment]
Does this fix the issue of building dependencies that are binary? Or just 5.9 compatibility

**Comment by gongzhang** [comment]
@bsneed Thank you! It works with Swift 5.9 and Xcode 15. I also fixed some warnings at: https://github.com/gongzhang/swift-create-xcframework/commit/18ef8cd6a4dcf9b404959f30eacdffcfd2d0ffcc

**Comment by Narayane** [comment]
Hi,

is it possible to merge this PR if all is ok to allow people like me to move on?

Thanks.

**Comment by czee** [comment]
+1

**Comment by ariedov** [comment]
This literally saved my as now. Please merge and release.

**Comment by ValentinaIancu-Gini** [comment]
Hi, I'm also waiting for this fix to be merged and released. Thanks!

**Comment by Narayane** [comment]
Hi,
Any progress on this point?

**Comment by ninjazoete** [comment]
Wow, guys this is exactly what I have problem with. Any update here ?

**Comment by Narayane** [comment]
cc @bok- @giginet

**Comment by giginet** [comment]
I'm not a maintainer of this product.

This product uses `swift package generate-xcodeproj` to generate XCFramework from Swift packages.
However, this feature has been obsoleted since Swift 5.6. so it's no longer maintained.
So, this feature may not work for the spec of the recent package manifest.

In my opinion, I feel it's difficult to maintain this product with this mechanism anymore.

**Comment by Narayane** [comment]
> @bsneed Thank you! It works with Swift 5.9 and Xcode 15. I also fixed some warnings at: [gongzhang@18ef8cd](https://github.com/gongzhang/swift-create-xcframework/commit/18ef8cd6a4dcf9b404959f30eacdffcfd2d0ffcc)

@gongzhang Could you open a pull request on @bsneed repository to merge your relative improvements and so have the last updated code in a single place?

**Comment by bsneed** [comment]
I've moved the repo over to my employer's GitHub since we rely on it.  I'll make some updates and get it available on brew shortly.

**Comment by bsneed** [comment]
Maintained fork here: https://github.com/segment-integrations/swift-create-xcframework

**Comment by bsneed** [comment]
@nonlin I can't speak for unsignedapps.  Given the lack of activity it seems like it, but not sure.

**Pull request closed without merging**
